# -*- coding: utf-8 -*-
"""Cerveja.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1drU4rWneAOGnkYjQAHux33oP059VAX1j
"""

import pandas as pd

df = pd.read_excel('dados_cerveja.xlsx')
df

# Definir features

features = ['temperatura','copo','espuma','cor']
target_resposta = 'classe' # aprenderá com ela

# Criar o modelo
from sklearn import tree

X = df[features]
y = df[target_resposta]

# Todas as variáveis devem ser do tipo numérico:
# Variáveis dummies:
# mud = 1, pint = 0
# sim = 1, não = 0

X.replace({
    'mud':1,'pint':2,
    'sim':1,'não':0,
    'clara':0,'escura':1
})

model = tree.DecisionTreeClassifier()

X = X.replace({
    'mud':1,'pint':2,
    'sim':1,'não':0,
    'clara':0,'escura':1
})
model.fit(X=X, y=y)

# Mostrar a árvore
import matplotlib.pyplot as plt

plt.figure(dpi=300)

tree.plot_tree(model, feature_names=features,
               class_names=model.classes_,
               filled=True)

# Definir ponto de corte em faixas, por exemplo, no caso da idade, pode ser melhor para não tornar o modelo tão exaustivo

# Exemplo de como realizar a predição:
# proba = arvore.predict_proba([[1,1,1,1]])[0]
# pd.Series(proba, index=model.classes_)